unit TestUDadosAbastecimento;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, System.Variants, Vcl.DBCtrls, cxGraphics, cxCurrencyEdit, cxControls,
  Winapi.Windows, Vcl.Dialogs, cxContainer, Vcl.Forms, cxLookAndFeelPainters,
  Vcl.ExtCtrls, UDadosAbastecimento, Vcl.Controls, cxTextEdit, System.Classes,
  System.SysUtils, UDados, Winapi.Messages, cxLookAndFeels, Vcl.Graphics, Data.DB,
  Vcl.StdCtrls, Vcl.Buttons, cxEdit, Vcl.ComCtrls;

type
  // Test methods for class TFDadosAbastecimento

  TestTFDadosAbastecimento = class(TTestCase)
  strict private
    FFDadosAbastecimento: TFDadosAbastecimento;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestcxCEQtdPropertiesChange;
  end;

implementation

procedure TestTFDadosAbastecimento.SetUp;
begin
  FFDadosAbastecimento := TFDadosAbastecimento.Create;
end;

procedure TestTFDadosAbastecimento.TearDown;
begin
  FFDadosAbastecimento.Free;
  FFDadosAbastecimento := nil;
end;

procedure TestTFDadosAbastecimento.TestcxCEQtdPropertiesChange;
var
  Sender: TObject;
begin
  // TODO: Setup method call parameters
  FFDadosAbastecimento.cxCEQtdPropertiesChange(Sender);
  // TODO: Validate method results
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTFDadosAbastecimento.Suite);
end.

