unit TestUClasseAbastecimento;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, UClasseAbastecimento;

type
  // Test methods for class TAbastecimento

  TestTAbastecimento = class(TTestCase)
  strict private
    FAbastecimento: TAbastecimento;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  end;

implementation

procedure TestTAbastecimento.SetUp;
begin
  FAbastecimento := TAbastecimento.Create;
end;

procedure TestTAbastecimento.TearDown;
begin
  FAbastecimento.Free;
  FAbastecimento := nil;
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTAbastecimento.Suite);
end.

